# Step 3: Train model with Ensemble Features

In [5]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import mxnet as mx
from mxnet import gluon
from mxnet import ndarray as nd
from mxnet import autograd
from mxnet.gluon import nn

import h5py
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

In [6]:
ctx = mx.gpu() # GPU WORKING HERE

![image](https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/argmax.PNG)
![image](https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/entropy_softmax.PNG)

In [7]:
 # calculate the acc of model
def accuracy(output, labels):
    return nd.mean(nd.argmax(output, axis=1) == labels).asscalar() 
    # assclar() -> transofrm arrary to coresspoding scalar
    # argmax() -> find the maxmum value in muti dimentional arrary

# calculate the loss and acc of model
def evaluate(net, data_iter):
    loss, acc, n = 0., 0., 0.
    steps = len(data_iter) # iteration
    for data, label in data_iter:
        data, label = data.as_in_context(ctx), label.as_in_context(ctx)
        output = net(data)
        acc += accuracy(output, label)
        loss += nd.mean(softmax_cross_entropy(output, label)).asscalar() # Calculate cross entropy of softmax output and one-hot label.
    return loss/steps, acc/steps # return average loss and acc

# Load features vector in step 2

In [8]:
with h5py.File('features_train.h5', 'r') as f:
    #features_vgg = np.array(f['vgg'])
    features_resnet = np.array(f['resnet'])
    features_densenet = np.array(f['densenet'])
    features_inception = np.array(f['inception'])
    labels = np.array(f['labels']) # label of different dogs

In [9]:
from IPython.core.interactiveshell import InteractiveShell 
InteractiveShell.ast_node_interactivity = "all" # display muti result in jupyter

**Shape of features vector**

**Vgg is a old model, therefore using other 3 models to train new model here**

In [22]:
#features_vgg.shape
labels.shape
features_resnet.shape
features_densenet.shape
features_inception.shape

(10222L,)

(10222L, 2048L)

(10222L, 2208L)

(10222L, 2048L)

**Image-> Features of densenet, resnet and inception. And then Merge to obtain a new feature vector**

In [11]:
# Extract first two cloums as features
features_resnet = features_resnet.reshape(features_resnet.shape[:2])
features_inception = features_inception.reshape(features_inception.shape[:2])
# Merge 3 features
features = np.concatenate([features_resnet, features_densenet, features_inception], axis=-1)

In [16]:
features_densenet.shape
features_resnet.shape
features_inception.shape
features.shape

(10222L, 2208L)

(10222L, 2048L)

(10222L, 2048L)

(10222L, 6304L)

## Constrct iterator by ArrayDataset and DataLoader

In [17]:
X_train, X_val, y_train, y_val = train_test_split(features, labels, test_size=0.2) # use 20% data for validation data

#constrct dataset
dataset_train = gluon.data.ArrayDataset(nd.array(X_train), nd.array(y_train))
dataset_val = gluon.data.ArrayDataset(nd.array(X_val), nd.array(y_val))

batch_size = 128 # Size of mini-batch
data_iter_train = gluon.data.DataLoader(dataset_train, batch_size, shuffle=True) # shuffle sort of dataset
data_iter_val = gluon.data.DataLoader(dataset_val, batch_size)

## Constrct Model
![image](https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/softmax_loss.PNG)

**And we need set optimize and learning rate in [gluon.Trainer](https://zh.gluon.ai/chapter_optimization/adam-gluon.html)**

In [33]:
net = nn.Sequential() # define a Sequential network
with net.name_scope():
    net.add(nn.Dense(256, activation='relu'))
    net.add(nn.Dropout(0.5)) # prevent overfitting
    net.add(nn.Dense(120)) # 120 breeds dogs classification

net.initialize(ctx=ctx)
softmax_cross_entropy = gluon.loss.SoftmaxCrossEntropyLoss()
trainer = gluon.Trainer(net.collect_params(), 'adam', {'learning_rate': 1e-4, 'wd': 1e-5})
net

Sequential(
  (0): Dense(None -> 256, Activation(relu))
  (1): Dropout(p = 0.5)
  (2): Dense(None -> 120, linear)
)

## Train Model
![image](https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/record.PNG)

In [34]:
for epoch in range(50): # iterat 50 times
    # initialize parameters
    train_loss = 0.
    train_acc = 0.
    steps = len(data_iter_train)
    for data, label in data_iter_train: # shuffled train data with batch size 128
        data, label = data.as_in_context(ctx), label.as_in_context(ctx)
        
        with autograd.record(): # auto derivation of loss
            output = net(data)
            loss = softmax_cross_entropy(output, label)
        
        loss.backward() # derivation
        trainer.step(batch_size) 
        # 因为loss.backward()求出的梯度是一个batch的梯度之和，所以需要除以batch_size得到平均梯度，就在trainer.step(batch_size)中这样表示
        
        train_loss += nd.mean(loss).asscalar()
        train_acc += accuracy(output, label)
    
    val_loss, val_acc = evaluate(net, data_iter_val)
    print("Epoch %d. loss: %.4f, acc: %.2f%%, val_loss %.4f, val_acc %.2f%%" % (
        epoch+1, train_loss/steps, train_acc/steps*100, val_loss, val_acc*100))

Epoch 1. loss: 4.5870, acc: 5.29%, val_loss 3.8906, val_acc 28.16%
Epoch 2. loss: 3.4818, acc: 24.70%, val_loss 2.5015, val_acc 63.03%
Epoch 3. loss: 2.3550, acc: 47.39%, val_loss 1.4636, val_acc 78.58%
Epoch 4. loss: 1.6194, acc: 62.59%, val_loss 0.9511, val_acc 84.06%
Epoch 5. loss: 1.2121, acc: 70.86%, val_loss 0.7209, val_acc 85.97%
Epoch 6. loss: 0.9733, acc: 75.26%, val_loss 0.5839, val_acc 87.73%
Epoch 7. loss: 0.8166, acc: 78.99%, val_loss 0.5180, val_acc 87.82%
Epoch 8. loss: 0.7202, acc: 80.89%, val_loss 0.4620, val_acc 89.68%
Epoch 9. loss: 0.6612, acc: 81.90%, val_loss 0.4350, val_acc 89.24%
Epoch 10. loss: 0.5952, acc: 83.82%, val_loss 0.4122, val_acc 89.59%
Epoch 11. loss: 0.5422, acc: 84.93%, val_loss 0.3886, val_acc 89.49%
Epoch 12. loss: 0.5066, acc: 85.46%, val_loss 0.3788, val_acc 89.34%
Epoch 13. loss: 0.4878, acc: 86.22%, val_loss 0.3684, val_acc 89.54%
Epoch 14. loss: 0.4365, acc: 87.81%, val_loss 0.3545, val_acc 89.68%
Epoch 15. loss: 0.4178, acc: 87.97%, val_los

# Load feature vector of test data

In [35]:
with h5py.File('features_test.h5', 'r') as f:
    #features_vgg_test = np.array(f['vgg'])
    features_resnet_test = np.array(f['resnet'])
    features_densenet_test = np.array(f['densenet'])
    features_inception_test = np.array(f['inception'])

**Features mergy same as training part**

In [36]:
features_resnet_test = features_resnet_test.reshape(features_resnet_test.shape[:2])
features_inception_test = features_inception_test.reshape(features_inception_test.shape[:2])

features_test = np.concatenate([features_resnet_test, features_densenet_test, features_inception_test], axis=-1)

## Prediction

In [37]:
%%time
output = nd.softmax(net(nd.array(features_test).as_in_context(ctx))).asnumpy()

Wall time: 1.02 s


In [39]:
output.shape

(10357L, 120L)

**integration to submission format**

In [44]:
%%time
df = pd.read_csv('sample_submission.csv')

for i, c in enumerate(df.columns[1:]):
    df[c] = output[:,i]
    
#df.to_csv('pred.csv', index=None)

Wall time: 733 ms


In [45]:
df

id  affenpinscher  afghan_hound  \
0      000621fb3cbb32d8935728e48679680e   3.338809e-08  1.363769e-07   
1      00102ee9d8eb90812350685311fe5890   7.239021e-08  1.030238e-08   
2      0012a730dfa437f5f3613fb75efcd4ce   1.761396e-09  2.193402e-04   
3      001510bc8570bbeee98c8d80c8a95ec1   2.408999e-04  3.334786e-07   
4      001a5f3114548acdefa3d4da05474c2e   5.872858e-02  1.650531e-05   
5      00225dcd3e4d2410dd53239f95c0352f   5.303541e-06  4.330623e-03   
6      002c2a3117c2193b4d26400ce431eebd   3.927715e-07  1.799073e-07   
7      002c58d413a521ae8d1a5daeb35fc803   1.560831e-06  3.612611e-07   
8      002f80396f1e3db687c5932d7978b196   3.354319e-08  2.925018e-07   
9      0036c6bcec6031be9e62a257b1c3c442   4.857402e-10  6.359738e-08   
10     0041940322116ae58c38130f5a6f71f9   8.085355e-07  5.915217e-07   
11     0042d6bf3e5f3700865886db32689436   2.859133e-06  2.410148e-07   
12     004476c96f575879af4af471af65cae8   3.465929e-08  3.228750e-08   
13     00485d47de966a9437ad3b33ac193b6f   4.920213e-05  1.652063e-05   
14     00496f65de6cc319145ce97bd6e90360   2.581579e-09  3.819398e-06   
15     004bf14426d1a830d459a9e0c0721309   4.223531e-07  3.464178e-06   
16     004c3721eb88358f462cdcec6b2380b7   1.172232e-06  2.653029e-07   
17     00559f56aab7e0a7749220f6aed65162   4.891419e-05  3.688400e-05   
18     005b281f1a4d6f29d527c9585e9bd33c   8.368997e-06  7.047171e-08   
19     005b6c6c76fefd6b458ef6fb6e54da6e   4.531930e-10  1.335003e-04   
20     006870b49353779b25eeb91fed43c31a   1.187767e-03  3.420939e-05   
21     0068f3a21b159ece126a28580cdad7a0   3.289428e-07  1.202604e-06   
22     0069b1cc4546fc98f84f981bf9a0696a   1.296721e-07  1.735042e-10   
23     0077bc3c63486ff09d3774d956af8f76   9.176526e-08  1.016972e-06   
24     00780e5d2bf4f7e4b5f96d08ddde669a   1.562272e-07  2.279579e-05   
25     007ed71136966728f5c0936e23c8286b   5.915777e-08  4.115961e-07   
26     0081831ceb49cd64212c32b884036b82   5.401730e-10  4.510649e-07   
27     00846c0edd5aa4f10ee5e9b84d7310a6   3.635542e-07  7.544951e-06   
28     0092bd9e90a13403373fc0e9e1218938   2.485643e-09  2.534479e-06   
29     009a3c4f6626e4750f74ceb8e8ed8760   7.337597e-07  1.097292e-06   
...                                 ...            ...           ...   
10327  ff7e00f66ebf0042c5ccb74170eecb1a   7.398182e-07  3.799144e-06   
10328  ff8c3ee47324ecf110e147f29747952a   4.322288e-07  1.126986e-06   
10329  ff8f9a768544fda79ffad62576f4d129   8.037298e-07  4.745812e-05   
10330  ff8ff2e36aa2a20d5d8585e2f686dbda   3.129536e-06  1.979228e-06   
10331  ff9742bc22b5830176e85490cf54cdf7   1.976799e-06  1.074005e-06   
10332  ff9b317696e29ca8cd27da30a896edcd   9.611443e-07  5.184176e-07   
10333  ffa316c6db0919d6bad1a5ed483e6722   3.771000e-09  3.203589e-10   
10334  ffa76e07dc686174c2a55fdbdca68bb3   6.286600e-09  3.305869e-07   
10335  ffadae851b94ece57602da7edf72d689   4.830407e-09  9.364376e-09   
10336  ffb3a78e4a162c173219194687eb6054   3.641619e-06  9.265864e-06   
10337  ffb55dbaa32939c109ef42df0668e077   1.249867e-10  4.521611e-09   
10338  ffb68ded4a2247b3c011840ece0a605c   1.681756e-06  7.505609e-07   
10339  ffb8bceeac5b3f587f67391ad346d454   6.324501e-06  1.616254e-07   
10340  ffbb6663b38e903dbd1efa5dce2d0bbb   1.491918e-06  2.513393e-06   
10341  ffbcda9eb84339cc5be15fd9900596a2   2.969615e-07  4.433197e-06   
10342  ffbcf032231bb0b025f9070d42ab7e8f   7.440343e-09  1.521065e-06   
10343  ffc0233904f4d03afe1484be791e09d6   1.498213e-07  2.085052e-08   
10344  ffd06687c72445b0c6e8a130a0a8711a   1.012017e-05  9.225028e-04   
10345  ffd304c521f43819f3824177fd9efeb0   4.596905e-06  9.412197e-07   
10346  ffd3ce0566df4be8049c767a329faaf7   4.998032e-05  2.905404e-07   
10347  ffd87c3e44faa0e3ee5fbbdc4c63b59b   3.669754e-08  1.238055e-07   
10348  ffe2315cf566e039516f5a4a5e52ff1b   1.381749e-05  1.030055e-06   
10349  ffe42f4b4c50d4f18c2b34500f391152   2.148468e-08  3.634550e-06   
10350  ffe563b1b8c0dcd0797c4362c6754b96   5.692571e-05  6.942870e-03   
10351

**Loss is 0.26657**

---

![image](https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/rank_1.PNG)

# Play with this model

In [46]:
import mxnet as mx
from mxnet import autograd
from mxnet import gluon
from mxnet import image
from mxnet import init
from mxnet import nd
from mxnet.gluon.data import vision
from mxnet.gluon.model_zoo import vision as models
import numpy as np
from tqdm import tqdm

import matplotlib.pyplot as plt

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [47]:
ctx = mx.cpu() # use cpu   gpu will cause python stop working here

preprocessing = [
    image.ForceResizeAug((224,224)), # Make resize shorter edge to size augmenter.
    image.ColorNormalizeAug(mean=nd.array([0.485, 0.456, 0.406]), std=nd.array([0.229, 0.224, 0.225])) # Mean and std normalization
]

def transform(data, label):
    data = data.astype('float32') / 255  # transform type to float and do normalization
    for pre in preprocessing:
        data = pre(data) # preprocessing data
    
    data = nd.transpose(data, (2,0,1)) # Transpose image to N, H, W  Kaggle image is BGR but we need RGB here
    return data, nd.array([label]).asscalar().astype('float32') # return to ndARRARY

def get_features(net, data):
    features = []
    labels = []

    for X, y in tqdm(data): # tqdm to display the schedule
        feature = net.features(X.as_in_context(ctx)) # return target arrary of image features
        features.append(feature.asnumpy()) # asnumpy() -> convert to numpy array  superposition features
        labels.append(y.asnumpy()) # superposition labels
    
    features = np.concatenate(features, axis=0) # splice big data fast
    labels = np.concatenate(labels, axis=0)
    return features, labels

In [52]:
preprocessing[0] = image.ForceResizeAug((224,224))
imgs = vision.ImageFolderDataset('for_test', transform=transform)
data = gluon.data.DataLoader(imgs, 64)

#features_vgg, _ = get_features(models.vgg16_bn(pretrained=True, ctx=ctx), data)
features_resnet_test, _ = get_features(models.resnet152_v1(pretrained=True, ctx=ctx), data)
features_densenet_test, _ = get_features(models.densenet161(pretrained=True, ctx=ctx), data)

100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.08s/it]


In [53]:
preprocessing[0] = image.ForceResizeAug((299,299))
imgs_299 = vision.ImageFolderDataset('for_test', transform=transform)
data_299 = gluon.data.DataLoader(imgs_299, 64)

features_inception_test, _ = get_features(models.inception_v3(pretrained=True, ctx=ctx), data)

100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.06s/it]


In [54]:
features_resnet_test = features_resnet_test.reshape(features_resnet_test.shape[:2])
features_inception_test = features_inception_test.reshape(features_inception_test.shape[:2])

features_test = np.concatenate([features_resnet_test, features_densenet_test, features_inception_test], axis=-1)

In [55]:
features_test.shape

(9L, 6304L)

In [59]:
%%time
ctx = mx.gpu()
output = nd.softmax(net(nd.array(features_test).as_in_context(ctx))).asnumpy()

Wall time: 7 ms


In [61]:
df = pd.read_csv('play.csv')

for i, c in enumerate(df.columns[1:]):
    df[c] = output[:,i]
    
df

id  affenpinscher  afghan_hound  african_hunting_dog      airedale  \
0    gakki       0.003300  2.146267e-03         2.374506e-02  4.693337e-03   
1      lbj       0.010391  3.426854e-03         3.375243e-03  3.388047e-03   
2  lbj_dog       0.002522  2.641871e-03         2.419023e-02  6.603371e-04   
3  minghui       0.002394  1.505301e-03         2.959822e-03  1.297245e-03   
4  shiyuan       0.001131  9.817295e-02         1.452859e-02  2.528736e-04   
5      sjw       0.002359  2.539508e-03         3.031914e-03  2.468147e-04   
6     wifi       0.000003  1.934447e-07         2.280943e-08  2.860270e-06   
7   wifi_1       0.000001  8.924700e-08         7.369625e-09  2.967036e-07   
8      zjm       0.001544  1.453925e-02         2.367935e-04  2.430328e-04   

   american_staffordshire_terrier   appenzeller  australian_terrier  \
0                    1.467181e-03  5.373989e-02        3.295791e-03   
1                    1.024398e-02  2.715941e-02        1.742182e-03   
2                    1.211232e-05  3.938686e-03        1.117741e-03   
3                    1.244449e-03  2.990543e-02        2.967193e-02   
4                    1.650364e-04  2.471526e-02        6.515169e-03   
5                    1.971229e-03  2.586129e-02        1.602074e-03   
6                    3.943605e-07  4.538414e-07        2.819758e-06   
7                    1.479544e-08  4.251804e-08        9.052362e-07   
8                    1.788755e-03  1.716408e-03        6.008908e-03   

        basenji        basset        ...          toy_poodle   toy_terrier  \
0  1.068859e-02  9.301095e-04        ...            0.027639  7.054830e-04   
1  1.356574e-02  1.189596e-03        ...            0.010381  1.482023e-02   
2  1.864619e-03  4.635472e-04        ...            0.001561  1.189174e-03   
3  1.066965e-02  6.665795e-04        ...            0.000460  6.300951e-05   
4  2.078568e-02  8.253477e-04        ...            0.048205  9.456469e-04   
5  2.243339e-01  7.441605e-03        ...            0.007852  1.251200e-03   
6  3.786133e-07  1.058913e-06        ...            0.007200  8.603908e-07   
7  8.970682e-08  9.339616e-09        ...            0.000281  2.829024e-07   
8  1.152762e-03  2.270173e-03        ...            0.002381  5.656866e-05   

         vizsla  walker_hound    weimaraner  welsh_springer_spaniel  \
0  4.325586e-03  4.445586e-02  4.072518e-04            1.535987e-03   
1  1.788112e-03  5.032847e-04  1.256199e-02            7.862886e-03   
2  2.393864e-04  1.622491e-02  1.833896e-04            1.213803e-02   
3  3.236760e-03  1.686336e-02  1.086515e-03            3.462723e-04   
4  9.945760e-04  2.322860e-03  7.821865e-05            3.896379e-03   
5  7.197974e-04  1.414346e-02  6.925876e-05            7.288409e-03   
6  3.960791e-07  6.462409e-07  9.855820e-07            6.743753e-07   
7  2.562145e-07  5.826296e-08  5.146887e-08            2.088315e-08   
8  2.209296e-02  6.531134e-02  2.054053e-04            8.650993e-05   

   west_highland_white_terrier       whippet  wire-haired_fox_terrier  \
0                     0.001510  8.106782e-02             7.456132e-04   
1                     0.004149  2.245429e-02             7.563993e-04   
2                     0.003025  1.089650e-03             2.595427e-04   
3                     0.000417  1.717968e-02             2.195678e-02   
4                     0.005804  1.843704e-03             7.732998e-04   
5                     0.018366  8.551370e-03             5.842790e-03   
6                     0.000056  1.048744e-06             2.104093e-07   
7                     0.000002  3.687507e-07             6.574365e-08   
8                     0.002278  2.512626e-01             2.411311e-03   

   yorkshire_terrier  
0           0.075522  
1           0.006772  
2           0.022409  
3           0.016392  
4           0.057777  
5           0.005577  
6           0.000025  
7           0.000006  
8           0.019337  

[9 rows x 121 columns]

In [73]:
df1 = pd.read_csv('play_pred.csv')

In [106]:
wifi_1 = df[7:8]
del wifi_1['id']
wifi_1.max(axis=1)

7    0.999366
dtype: float32

99.9366% **pomeranian**  in predicted csv file

<img src="https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/wifi_1.jpg" width="400px" align="left"/>
<img src="https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/pomeranian.jpg" width="400px" align="middle"/>

In [102]:
lbj_dog = df[2:3]
del lbj_dog['id']
lbj_dog.max(axis=1)

2    0.181071
dtype: float32

0.181071 coresspoding **pembroke**  in predicted csv file

<img src="https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/lbj_dog.jpg" width="300px" align="left"/>
<img src="https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/pembroke.jpg" width="350px" align="middle"/>

In [100]:
gakki = df[0:1]
del gakki['id']
gakki.max(axis=1)

0    0.081068
dtype: float32

0.081068 coresspoding **whippet** in predicted csv file

<img src="https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/gakki.jpg" width="200px" align="left"/>
<img src="https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/whippet.jpg" width="250px" align="middle"/>

In [101]:
lbj = df[1:2]
del lbj['id']
lbj.max(axis=1)

1    0.070452
dtype: float32

0.070452 coresspoding **italian_greyhound**  in predicted csv file

<img src="https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/lbj.jpg" width="200px" align="left"/>
<img src="https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/italian_greyhound.jpg" width="300px" align="middle"/>

In [104]:
shiyuan = df[4:5]
del shiyuan['id']
shiyuan.max(axis=1)

4    0.138123
dtype: float32

0.138123 coresspoding **japanese_spaniel**  in predicted csv file

<img src="https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/shiyuan.jpg" width="400px" align="left"/>
<img src="https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/japanese_spaniel.jpg" width="150px" align="middle"/>

In [105]:
sjw = df[5:6]
del sjw['id']
sjw.max(axis=1)

5    0.224334
dtype: float32

 0.224334 coresspoding **basenji**  in predicted csv file

<img src="https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/sjw.jpg" width="400px" align="left"/>
<img src="https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/basenji.jpg" width="400px" align="middle"/>

In [107]:
zjm = df[8:9]
del zjm['id']
zjm.max(axis=1)

8    0.251263
dtype: float32

0.251263 coresspoding **whippet** in predicted csv file

<img src="https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/zjm.jpg" width="220px" align="left"/>
<img src="https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/whippet.jpg" width="250px" align="middle"/>

In [103]:
minghui = df[3:4]
del minghui['id']
minghui.max(axis=1)

3    0.255215
dtype: float32

0.255215 coresspoding **eskimo_dog**  in predicted csv file

<img src="https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/minghui.jpg" width="200px" align="left"/>
<img src="https://raw.githubusercontent.com/Trouble404/Kaggle-Dog-breed-Identification/master/readme_pic_add/eskimo_dog.jpg" width="350px" align="middle"/>